config/routes.rb
Rails.application.routes.draw do

  resources :cards do
    member do
      get :choose_design
      post :update_design

      get :get_photo
      post :update_photo

      get :processing

      get :preview

      get :deliver

      patch :thanks

      get :pngify

    end
  end

  get 'pages/about'

  root 'welcome#index'

  mount Shrine.download_endpoint => "/attachments"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord

  include ImageUploader[:photo]

  validates :email, format: { with: /.*@.*/, message: "has to have an @ sign" }, allow_nil: true
end

app/models/image_uploader.rb
require "image_processing/mini_magick"

class ImageUploader < Shrine


    plugin :activerecord
    plugin :determine_mime_type
    plugin :validation_helpers
    plugin :processing
    plugin :versions
    plugin :delete_raw


    Attacher.validate do
      validate_min_size 1, message: "must not be empty"
      validate_max_size 5*1024*1024, message: "is too large (max is 5 MB)"
      validate_mime_type_inclusion  %w[image/jpeg image/png image/tiff]
      validate_extension_inclusion  %w[jpg jpeg png tiff tif]
    end

    process(:store) do |io, context|
      versions = { original: io }

      io.download do |original|
        pipeline = ImageProcessing::MiniMagick.source(original)

        versions[:small] = pipeline.resize_to_fill!(610,865)
      end

      versions
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def index3
  end

  def show
  end

  def create
    card = Card.create(team: params[:team])

    redirect_to choose_design_card_path(card)
  end

  def choose_design
    @card = Card.find(params[:id])
  end

  def update_design
    @card = Card.find(params[:id])

    @card.update_attributes(design: params[:design])

    redirect_to get_photo_card_path(@card)
  end

  def get_photo
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])

      if @card.update(card_params)
      redirect_to preview_card_path

      else
        render :get_photo
      end
  end


  def preview
    @card = Card.find(params[:id])
  end

  def deliver
    @card = Card.find(params[:id])
  end

  def thanks
    @card = Card.find(params[:id])
    if @card.update(card_params)
      CardMailer.thank_you_email(@card).deliver_later
    else
      flash[:notice] = "You must enter a valid email"
      redirect_to deliver_card_path(@card)
      return
    end

    render layout: false
  end

  def new
  end


  def card_params
    params.require(:card).permit(:number, :name, :position, :photo, :info, :email)
  end


  def pngify
    @card = Card.find(params[:id])

      respond_to do |format|
        if @card.errors.any?
          @card.errors.full_messages
        else
          format.html { render "cards/templates/#{@card.design}", layout: false }
          format.png do
            kit = IMGKit.new(pngify_card_url(@card), width: 200, height: 1040)

            send_data kit.to_img(:png), type: "image/png", disposition: 'inline'
         end
       end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout false

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_card(card)
    kit = IMGKit.new("https://github.com/404")

    kit.to_file('output.png')
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cards/choose_design.html.erb
<% if @card.team == "rays" %>
  <%= render partial: "cards/designs/rays" %>
<% end %>

<% if @card.team == "bucs" %>
    <%= render partial: "cards/designs/bucs" %>
<% end %>

<% if @card.team == "bolts" %>
    <%= render partial: "cards/designs/bolts" %>
<% end %>

app/views/cards/deliver.html.erb
<section class="steps preview">
  <div class="" id="">
    <h1></h1>
  </div>
</section>
<div class="preview-card">
  <div class="finish">
    <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
      <%= image_tag(pngify_card_url(@card, format: "png"), class: "pngify") %>

      <div class="form-group card-info">
          <h4>Enter your email to receive your card.</h4>
      </div>

      <%= form_for @card, url: thanks_card_path(@card) do |f| %>

      <div class="form-group send">
        <p>
          <%= f.text_field :email, class: "form-control info", placeholder: "your email" %>
        </p>
        <p id="notice"><%= notice %></p>
      </div>

      <div class="form-group">
        <%= f.submit "Send", class: "done" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cards/designs/_bolts.html.erb
<section class="steps">
  <div class="" id="circle">
    <h1>2</h1>
  </div>
  <div class="subhead">
    <h5>Choose your design</h5>
  </div>
  <div class="visible">
    <h6><i class="arrow down"></i></h6>
    <h6><i class="arrow down"></i></h6>  </div>
</section>
<section class="design">
  <div class="team-cards">
    <%= link_to update_design_card_path(@card, design: "bolts_a"), method: :post do %>
      <% image_tag("tampacards/bolts_template_a.png", size: "250x350", alt: "Palms & Pucks") %>
    <% end %>
  </div>
  <div class="team-cards">
    <%= link_to update_design_card_path(@card, design: "bolts_b"), method: :post do %>
      <% image_tag("tampacards/bolts_template_b.png", size: "250x350", alt: "Championship") %>
    <% end %>
  </div>
  <div class="team-cards">
    <%= link_to update_design_card_path(@card, design: "bolts_c"), method: :post do %>
        <% image_tag("tampacards/bolts_template_c.png", size: "250x350", alt: "Black") %>
    <% end %>
  </div>
</section>

app/views/cards/designs/_bucs.html.erb
<section class="steps">
  <div class="" id="circle">
    <h1>2</h1>
  </div>
  <div class="subhead">
    <h5>Choose your design</h5>
  </div>
  <div class="visible">
    <h6><i class="arrow down"></i></h6>
    <h6><i class="arrow down"></i></h6>  </div>
</section>
<section class="design">
  <div class="team-cards">
    <%= link_to update_design_card_path(@card, design: "bucs_a"), method: :post do %>
      <% image_tag("tampacards/bucs_template_a.png", size: "250x350", alt: "Footballs") %>
    <% end %>
  </div>
  <div class="team-cards">
    <%= link_to update_design_card_path(@card, design: "rays_b"), method: :post do %>
      <% image_tag("tampacards/bucs_template_b.png", size: "250x350", alt: "Stadium") %>
    <% end %>
  </div>
  <div class="team-cards">
    <%= link_to update_design_card_path(@card, design: "rays_d"), method: :post do %>
        <% image_tag("tampacards/bucs_template_c.png", size: "250x350", alt: "Pirate") %>
    <% end %>
  </div>
</section>

app/views/cards/designs/_rays.html.erb
<section class="steps">
  <div class="" id="circle">
    <h1>2</h1>
  </div>
  <div class="subhead">
    <h5>Choose your design</h5>
  </div>
  <div class="visible">
    <h6><i class="arrow down"></i></h6>
    <h6><i class="arrow down"></i></h6>  </div>
</section>
<section class="design">
  <div class="team-cards">
    <%= link_to update_design_card_path(@card, design: "rays_a"), method: :post do %>
      <% image_tag("tampacards/rays_template_a.png", size: "250x350", alt: "Baseballs") %>
    <% end %>
  </div>
  <div class="team-cards">
    <%= link_to update_design_card_path(@card, design: "rays_b"), method: :post do %>
      <% image_tag("tampacards/rays_template_b.png", size: "250x350", alt: "Stadium") %>
    <% end %>
  </div>
  <div class="team-cards">
    <%= link_to update_design_card_path(@card, design: "rays_c"), method: :post do %>
        <% image_tag("tampacards/rays_template_c.png", size: "250x350", alt: "Raymond") %>
    <% end %>
  </div>
  <div class="team-cards">
    <%= link_to update_design_card_path(@card, design: "rays_d"), method: :post do %>
        <% image_tag("tampacards/rays_template_d.png", size: "250x350", alt: "DJ Kitty") %>
    <% end %>
  </div>
</section>

app/views/cards/designs/templates/eagles_a.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= stylesheet_link_tag 'pngify' %>
    <title>card</title>
  </head>
  <body>
      <div class="background">
        <%= image_tag("eagles_a.png") %>
      </div>
      <div class="info">
        <%= @card.name %>
      </div>
      <div class="image">
        <%= image_tag(@card.photo_url, size: "200x275") %>
      </div>
  </body>
</html>

app/views/cards/designs/templates/eagles_b.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= stylesheet_link_tag 'pngify' %>
    <title>card</title>
  </head>
  <body>
      <div class="background">
        <%= image_tag("eagles_b.png") %>
      </div>
      <div class="info">
        <%= @card.name %>
      </div>
      <div class="image">
        <%= image_tag(@card.photo_url, size: "200x275") %>
      </div>
  </body>
</html>

app/views/cards/get_photo.html.erb
<section class="steps">
  <div class="" id="circle">
    <h1>3</h1>
  </div>
  <div class="subhead">
    <h5>Upload your photo and information</h5>
  </div>
</section>
  <div class="front-card card-info">
    <div class="col-lg-12">
      <h3>Front of Card</h3>

        <h4>Choose a Photo for your card</h4>


        <%= form_for @card do |f| %>
          <% if @card.errors.any? %>
            <div class="error-card" id="error_explanation">
                  <p>
                  <% @card.errors.full_messages.each do |message| %>
                  <%= message %>
                  </p>
                <% end %>
            </div>
          <% end %>

            <div class="form-group info">
              <%= f.hidden_field :photo, value: @card.cached_photo_data %>
              <%= f.file_field :photo, required: true %>
            </div>


          <h4>Enter your Name</h4>

          <div class="form-group info name">

            <p>
              <%= f.text_field :name, class: "form-control" %>
              <%= f.label :name, "Name (20 character maximum)" %>
            </p>

          </div>

          <div class="card-label">
              <%= f.submit "Preview", class: "done" %>
          </div>

        <% end %>
    </div>
  </div>

app/views/cards/index.html.erb
<section class="steps">
  <div class="" id="circle">
    <h1>1</h1>
  </div>
  <div class="subhead">
    <h5>Choose your team</h5>
  </div>
  <div class="visible">
    <h6><i class="arrow down"></i></h6>
    <h6><i class="arrow down"></i></h6>
  </div>
</section>
<section class="teams switch">
  <div class="team-cards category">
    <%= link_to cards_path(team: "rays"), method: :post do %>
      <% image_tag("tampacards/rays_mock_b.png", size: "200x350", alt: "Rays") %>
    <% end %>
  </div>
  <div class="team-cards category">
    <%= link_to cards_path(team: "bucs"), method: :post do %>
      <% image_tag("tampacards/bucs_mock_c.png", size: "200x350", alt: "Bucs") %>
    <% end %>
  </div>
  <div class="team-cards category">
    <%= link_to cards_path(team: "bolts"), method: :post do %>
      <% image_tag("tampacards/bolts_mock_c.png", size: "200x350", alt: "Bolts") %>
    <% end %>
  </div>
</section>

app/views/cards/new.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Photo Card</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  </body>
</html>

app/views/cards/preview.html.erb
<section class="steps preview">
      <div class="preview" id="">
        <h1>PREVIEW</h1>
      </div>
</section>
<section class="teams">
    <div class="preview-card">
      <div class="spinner sk-fading-circle">
        <div class="sk-circle1 sk-circle"></div>
        <div class="sk-circle2 sk-circle"></div>
        <div class="sk-circle3 sk-circle"></div>
        <div class="sk-circle4 sk-circle"></div>
        <div class="sk-circle5 sk-circle"></div>
        <div class="sk-circle6 sk-circle"></div>
        <div class="sk-circle7 sk-circle"></div>
        <div class="sk-circle8 sk-circle"></div>
        <div class="sk-circle9 sk-circle"></div>
        <div class="sk-circle10 sk-circle"></div>
        <div class="sk-circle11 sk-circle"></div>
        <div class="sk-circle12 sk-circle"></div>
      </div>
      <!-- <div class="spinner sk-cube-grid">
        <div class="sk-cube sk-cube1"></div>
        <div class="sk-cube sk-cube2"></div>
        <div class="sk-cube sk-cube3"></div>
        <div class="sk-cube sk-cube4"></div>
        <div class="sk-cube sk-cube5"></div>
        <div class="sk-cube sk-cube6"></div>
        <div class="sk-cube sk-cube7"></div>
        <div class="sk-cube sk-cube8"></div>
        <div class="sk-cube sk-cube9"></div>
      </div> -->

        <%= image_tag(pngify_card_url(@card, format: "png"), class: "pngify") %>

      <div class="finish">
        <div class="middle">
          <%= link_to get_photo_card_path, method: :get do %>
          <%= submit_tag "Edit", class: "submit" %>
          <% end %>
          <%= link_to deliver_card_path, method: :get do %>
          <%= submit_tag "Email Card", class: "done" %>
          <% end %>
        </div>
      </div>
    </div>
</section>

app/views/cards/processing.html.erb
<meta HTTP-EQUIV="REFRESH" content="7; url=<%= preview_card_path(@card) %>">

<section class="steps preview">
  <div class="" id="">
    <h1>NICELY DONE!</h1>
  </div>
  <div class="subhead">
    <h5></h5>
  </div>
</section>
  <div class="sk-cube-grid">
    <div class="sk-cube sk-cube1"></div>
    <div class="sk-cube sk-cube2"></div>
    <div class="sk-cube sk-cube3"></div>
    <div class="sk-cube sk-cube4"></div>
    <div class="sk-cube sk-cube5"></div>
    <div class="sk-cube sk-cube6"></div>
    <div class="sk-cube sk-cube7"></div>
    <div class="sk-cube sk-cube8"></div>
    <div class="sk-cube sk-cube9"></div>
  </div>
  <div class="steps">
    <h2>A FUN FACT while you wait...</h2>
    <p>The fastest game ever played in baseball was 51 minutes on September 28, 1919 between the Philadelphia Phillies and the New York Giants.</p>
  </div>

app/views/cards/templates/bolts_a.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= stylesheet_link_tag 'pngify' %>
    <title>card</title>
  </head>
  <body>
      <div class="background">
        <%= image_tag("tampacards/bolts_a.png") %>
      </div>
      <div class="info">
        <%= @card.name %>
      </div>
      <div class="image">
        <%= image_tag(@card.photo_url(:small)) %>
      </div>
  </body>
</html>

app/views/cards/templates/bolts_b.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= stylesheet_link_tag 'pngify' %>
    <title>card</title>
  </head>
  <body>
      <div class="background">
        <%= image_tag("tampacards/bolts_b.png") %>
      </div>
      <div class="info">
        <%= @card.name %>
      </div>
      <div class="image">
        <%= image_tag(@card.photo_url(:small)) %>
      </div>
  </body>
</html>

app/views/cards/templates/bolts_c.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= stylesheet_link_tag 'pngify' %>
    <title>card</title>
  </head>
  <body>
      <div class="background">
        <%= image_tag("tampacards/bolts_c.png") %>
      </div>
      <div class="info">
        <%= @card.name %>
      </div>
      <div class="image">
        <%= image_tag(@card.photo_url(:small)) %>
      </div>
  </body>
</html>

app/views/cards/templates/bucs_c.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= stylesheet_link_tag 'pngify' %>
    <title>card</title>
  </head>
  <body>
      <div class="background">
        <%= image_tag("tampacards/bucs_c.png") %>
      </div>
      <div class="info">
        <%= @card.name %>
      </div>
      <div class="image">
        <%= image_tag(@card.photo_url(:small)) %>
      </div>
  </body>
</html>

app/views/cards/templates/eagles_a.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= stylesheet_link_tag 'pngify' %>
    <title>card</title>
  </head>
  <body>
      <div class="background">
        <%= image_tag("phillycards/eagles_a.png") %>
      </div>
      <div class="info">
        <%= @card.name %>
      </div>
      <div class="image">
        <%= image_tag(@card.photo_url(:small)) %>
      </div>
  </body>
</html>

app/views/cards/templates/ironyardcard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= stylesheet_link_tag 'pngify' %>
    <title>card</title>
  </head>
  <body>
      <div class="background">
        <%= image_tag("bucs_b.png") %>
      </div>
      <div class="info">
        <%= @card.name %>
      </div>
      <div class="image">
        <%= image_tag(@card.photo_url, size: "200x275") %>
      </div>
  </body>
</html>

app/views/cards/templates/rays_b.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= stylesheet_link_tag 'pngify' %>
    <title>card</title>
  </head>
  <body>
      <div class="background">
        <%= image_tag("tampacards/rays_b.png") %>
      </div>
      <div class="info">
        <%= @card.name %>
      </div>
      <div class="image">
        <%= image_tag(@card.photo_url(:small)) %>
      </div>
  </body>
</html>

app/views/cards/templates/rays_blank.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= stylesheet_link_tag 'pngify' %>
    <title>card</title>
  </head>
  <body>
      <div class="background">
        <%= image_tag("rays_blank.png") %>
      </div>
      <div class="info">
        <%= @card.name %>
      </div>
      <div class="image">
        <%= image_tag(@card.photo_url, size: "200x275") %>
      </div>
  </body>
</html>

app/views/cards/templates/rays_d.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= stylesheet_link_tag 'pngify' %>
    <title>card</title>
  </head>
  <body>
      <div class="background">
        <%= image_tag("tampacards/rays_d.png") %>
      </div>
      <div class="info">
        <%= @card.name %>
      </div>
      <div class="image">
        <%= image_tag(@card.photo_url(:small)) %>
      </div>
  </body>
</html>

app/views/cards/templates/sixers_a.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= stylesheet_link_tag 'pngify' %>
    <title>card</title>
  </head>
  <body>
      <div class="background">
        <%= image_tag("phillycards/sixers_a.png") %>
      </div>
      <div class="info">
        <%= @card.name %>
      </div>
      <div class="image">
        <%= image_tag(@card.photo_url(:small)) %>
      </div>
  </body>
</html>

app/views/cards/templates/starwarscard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= stylesheet_link_tag 'pngify' %>
    <title>card</title>
  </head>
  <body>
      <div class="background">
        <%= image_tag("starwarscard.png") %>
      </div>
      <div class="info">
        <%= @card.name %>
      </div>
      <div class="image">
        <%= image_tag(@card.photo_url, size: "200x275") %>
      </div>
  </body>
</html>

app/views/cards/templates/teamdewey_blank.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= stylesheet_link_tag 'pngify' %>
    <title>card</title>
  </head>
  <body>
      <div class="background">
        <%= image_tag("teamdewey_blank.png") %>
      </div>
      <div class="info">
        <%= @card.name %>
      </div>
      <div class="image">
        <%= image_tag(@card.photo_url, size: "200x275") %>
      </div>
  </body>
</html>

app/views/cards/templates/teamstark_blank.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= stylesheet_link_tag 'pngify' %>
    <title>card</title>
  </head>
  <body>
      <div class="background">
        <%= image_tag("teamstark_blank.png") %>
      </div>
      <div class="info">
        <%= @card.name %>
      </div>
      <div class="image">
        <%= image_tag(@card.photo_url, size: "200x275") %>
      </div>
  </body>
</html>

app/views/cards/thanks.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Photo Card</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="wrapper">
      <section class="thanks logo">
        <div class="" id="">
          <%= link_to root_path, method: :get do %>
          <%= image_tag("mysportscardtampa.png", size: "250x250", alt: "My Sports Card") %>
          <% end %>
          <h1>THANK YOU!</h1>
        </div>
        <div class="thanks">
          <h5>you will receive your card momentarily</h5>
        </div>
      </section>
      <div class="start">
        <%= link_to cards_path, method: :get do %>
        <%= submit_tag "Create A New Card", class: "done" %>
        <% end %>
      </div>
    </div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Photo Card</title>

    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'cards', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap -->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">


  </head>

  <body>

    <header class="topbar">

      <nav class="navbar navbar-fixed-top" role="navigation">
        <div class="horizontal-logo">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <div class="to-close hamb">
                  <div class="x">
                    <input type="checkbox" id="menu-x" />
                    <label for="menu-x"><span></span></label>
                  </div>
                </div>
            </button>
            <%= link_to root_path, method: :get do %>
            <%= image_tag("mysportscard_horizontal.png", size: "150x50", alt: "My Sports Card", class: "hlogo") %>
            <% end %>
          </div>
          <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav nav-links">
              <li><%= link_to "Make New Card", cards_path %></li>
                <li><%= link_to "About", pages_about_path %></li>
                <!--<li><%= link_to "Home", root_path %></li>-->
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <%= yield %>


  </body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en" >
  <head>
    <meta property="og:url" content="https://photocard.herokuapp.com" />
    <meta name="title" property="og:title" content="Photo Card Tampa">
    <meta property="og:type" content="website">
    <meta name="image" property="og:image" content="https://quotified.herokuapp.com/assets/photodemo.png">
    <meta name="description" property="og:description" content="This app allows a user upload a photo and create a sports, digital trading card from their favorite Tampa team.">
    <meta name="author" content="Julius J Bzozowski III">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title>
      <%= 'Photo Card Tampa' %>
    </title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <section class="wrapper">
      <%= link_to cards_path, method: :get do %>
      <div class = "landing container-fluid">
      </div>
      <% end %>
    </section>
      <div class="start">
        <%= link_to cards_path, method: :get do %>
        <%= submit_tag "Start Here", class: "begin" %>
        <% end %>
      </div>
      <div class="intro-text">
        <h3>Create a personalized trading card to use as a screen saver, post online or share with friends.<br> It's FUN, EASY and FREE!</h3>
      </div>
  </body>
</html>